CREATE TABLE IF NOT EXISTS kb_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    manager VARCHAR(50),
    phone VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kb_asset_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kb_supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    contact_person VARCHAR(50),
    phone VARCHAR(30),
    address VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kb_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code VARCHAR(40) NOT NULL UNIQUE,
    asset_name VARCHAR(120) NOT NULL,
    category_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    purchase_date DATE,
    original_value NUMERIC(12, 2) DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_STOCK',
    keeper VARCHAR(50),
    remark VARCHAR(300),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_asset_category FOREIGN KEY (category_id) REFERENCES kb_asset_category(id),
    CONSTRAINT fk_asset_department FOREIGN KEY (department_id) REFERENCES kb_department(id),
    CONSTRAINT fk_asset_supplier FOREIGN KEY (supplier_id) REFERENCES kb_supplier(id),
    CONSTRAINT ck_asset_status CHECK (status IN ('IN_STOCK', 'IN_USE', 'REPAIR', 'SCRAPPED'))
);

COMMENT ON TABLE kb_department IS '使用部门表';
COMMENT ON TABLE kb_asset_category IS '设备分类表';
COMMENT ON TABLE kb_supplier IS '供应商表';
COMMENT ON TABLE kb_asset IS '教学设备资产表';
